// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGwxq_quRcJk13xhCwy9MWT1TELIdzvOI',
    appId: '1:182331722242:web:b8a7b478d774728935751b',
    messagingSenderId: '182331722242',
    projectId: 'fluck-app-fv0kh',
    authDomain: 'fluck-app-fv0kh.firebaseapp.com',
    storageBucket: 'fluck-app-fv0kh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtNexiObCNaurgfpFlqFj-zf5vpWkAzGY',
    appId: '1:182331722242:android:bc835ac0fac1b69435751b',
    messagingSenderId: '182331722242',
    projectId: 'fluck-app-fv0kh',
    storageBucket: 'fluck-app-fv0kh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2etOCaH2OX3-SJBIXl4A7JbFE6bjOBy4',
    appId: '1:182331722242:ios:db7cc4849d193ba035751b',
    messagingSenderId: '182331722242',
    projectId: 'fluck-app-fv0kh',
    storageBucket: 'fluck-app-fv0kh.firebasestorage.app',
    iosBundleId: 'com.hashus303.fluck',
  );
}
